### ISSUE TITLE
Imports for other operating systems cause parsing issues for the current platform

### ISSUE THREAD

**Issue by YuKitsune** [YuKitsune/dingus#32]
When running dingus on a nix system and an import exists for Windows, the Windows-specific import causes a load failure:

```yaml
imports:
  - alias: packages
    source: ./nix/dingus.packages.yaml
    platforms: [macOS, Linux]
  - alias: packages
    source: windows\dingus.packages.yaml
    platform: Windows
```

This seems to be because the Windows-style path can't be interpreted on nix-based systems, but Dingus doesn't use the `platform` field to skip the import, it just applies it to the parent command.
